import { Injectable, NotFoundException, BadRequestException, ForbiddenException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { AppointmentStatus, ClinicRole, Prisma } from '@prisma/client';
import { AccessControlService } from '../common/profanity/access-control/access-control.service';
import { JwtUser } from '../common/profanity/access-control/type/jwt-user';
import { ZoomService } from '../zoom/zoom.service';

@Injectable()
export class AppointmentsService {
  constructor(private prisma: PrismaService, private readonly accessControl: AccessControlService, private readonly zoom: ZoomService) {}
  private getClinicId(user: JwtUser) { if (!user.clinicId) throw new ForbiddenException('Clinic context is required'); return user.clinicId; }
  async bookAppointment(patientUserId: number, slotId: number, _user: JwtUser) { return this.prisma.$transaction(async tx => { const patient = await tx.patient.findUnique({ where: { userId: patientUserId } }); if (!patient) throw new NotFoundException('Patient not found'); const slot = await tx.appointmentSlot.findUnique({ where: { id: slotId }, include: { doctor: { include: { clinic: true } } } }); if (!slot || !slot.clinicId || !slot.doctor.clinicId || slot.clinicId !== slot.doctor.clinicId || !slot.doctor.clinic?.isActive) throw new NotFoundException('Slot not found'); if (slot.isBooked) throw new BadRequestException('Slot already booked'); if (slot.startTime <= new Date()) throw new BadRequestException('Cannot book past appointments'); const clinicId = slot.clinicId; await tx.clinicPatient.upsert({ where: { clinicId_patientId: { clinicId, patientId: patient.id } }, update: {}, create: { clinicId, patientId: patient.id } }); const existing = await tx.appointment.findFirst({ where: { clinicId, patientId: patient.id, date: slot.startTime, status: { in: [AppointmentStatus.PENDING, AppointmentStatus.CONFIRMED] } } }); if (existing) throw new BadRequestException('You already have an appointment at this time'); const claimed = await tx.appointmentSlot.updateMany({ where: { id: slotId, clinicId, isBooked: false }, data: { isBooked: true } }); if (claimed.count !== 1) throw new BadRequestException('Slot already booked'); return tx.appointment.create({ data: { clinicId, doctorId: slot.doctorId, patientId: patient.id, slotId: slot.id, date: slot.startTime, status: AppointmentStatus.PENDING }, include: { clinic: { select: { id: true, name: true, slug: true } }, doctor: { include: { clinic: true } }, patient: true, slot: true } }); }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable }); }
  async getDoctorAppointments(userId: number, user: JwtUser) { const clinicId = this.getClinicId(user); const doctor = await this.prisma.doctor.findFirst({ where: { userId, clinicId } }); if (!doctor) throw new NotFoundException('Doctor not found'); return this.prisma.appointment.findMany({ where: { clinicId, doctorId: doctor.id }, include: { patient: { include: { user: { select: { email: true } } } }, slot: true }, orderBy: { date: 'asc' } }); }
  async getPatientAppointments(userId: number, _user: JwtUser) { const patient = await this.prisma.patient.findUnique({ where: { userId } }); if (!patient) throw new NotFoundException('Patient not found'); return this.prisma.appointment.findMany({ where: { patientId: patient.id }, include: { clinic: { select: { id: true, name: true, slug: true } }, doctor: { include: { clinic: { select: { id: true, name: true, slug: true } }, user: { select: { email: true } } } }, slot: true }, orderBy: { date: 'asc' } }); }
  async confirmAppointment(id: number, user: JwtUser) { await this.accessControl.verifyDoctorAppointment(id, user); return this.prisma.appointment.update({ where: { id }, data: { status: AppointmentStatus.CONFIRMED } }); }
  async completeAppointment(id: number, user: JwtUser) { await this.accessControl.verifyDoctorAppointment(id, user); return this.prisma.appointment.update({ where: { id }, data: { status: AppointmentStatus.COMPLETED } }); }
  async cancelAppointment(id: number, user: JwtUser) { const appointment = await this.accessControl.verifyPatientAppointment(id, user); return this.prisma.$transaction(async tx => { const updated = await tx.appointment.update({ where: { id }, data: { status: AppointmentStatus.CANCELLED } }); await tx.appointmentSlot.updateMany({ where: { id: appointment.slotId, clinicId: appointment.clinicId ?? undefined, isBooked: true }, data: { isBooked: false } }); return updated; }); }
  async cancelAppointmentByDoctor(id: number, user: JwtUser) { const appointment = await this.accessControl.verifyDoctorAppointment(id, user); return this.prisma.$transaction(async tx => { const updated = await tx.appointment.update({ where: { id }, data: { status: AppointmentStatus.CANCELLED } }); await tx.appointmentSlot.updateMany({ where: { id: appointment.slotId, clinicId: appointment.clinicId ?? undefined, isBooked: true }, data: { isBooked: false } }); return updated; }); }
  async setMeetingLink(id: number, user: JwtUser, meetingLink: string) { await this.accessControl.verifyDoctorAppointment(id, user); return this.prisma.appointment.update({ where: { id }, data: { meetingLink } }); }
  async generateZoomMeetingLink(id: number, user: JwtUser) { await this.accessControl.verifyDoctorAppointment(id, user); const appointment = await this.prisma.appointment.findUnique({ where: { id }, include: { slot: true, patient: true, doctor: true } }); if (!appointment) throw new NotFoundException('Appointment not found'); const meeting = await this.zoom.createMeeting({ topic: `كشف مع د. ${appointment.doctor.fullName} - ${appointment.patient.fullName}`, startTime: appointment.slot.startTime, durationMinutes: Math.max(15, Math.round((appointment.slot.endTime.getTime() - appointment.slot.startTime.getTime()) / 60000)) }); return this.prisma.appointment.update({ where: { id }, data: { meetingLink: meeting.join_url } }); }
  async removeMeetingLink(id: number, user: JwtUser) { await this.accessControl.verifyDoctorAppointment(id, user); return this.prisma.appointment.update({ where: { id }, data: { meetingLink: null } }); }
  async getAvailableSlots(doctorId: number, _user?: JwtUser) { const doctor = await this.prisma.doctor.findFirst({ where: { id: doctorId, clinic: { isActive: true } } }); if (!doctor || !doctor.clinicId) throw new NotFoundException('Doctor not found'); return this.prisma.appointmentSlot.findMany({ where: { clinicId: doctor.clinicId, doctorId, isBooked: false, startTime: { gt: new Date() } }, orderBy: { startTime: 'asc' } }); }
  private buildSlotsForDay(clinicId: number, doctorId: number, date: Date, startHour: number, endHour: number, duration: number) { const start = new Date(date); start.setHours(startHour,0,0,0); const end = new Date(date); end.setHours(endHour,0,0,0); const slots: { clinicId:number; doctorId:number; startTime:Date; endTime:Date }[]=[]; while(start<end){const slotStart=new Date(start);const slotEnd=new Date(start);slotEnd.setMinutes(slotEnd.getMinutes()+duration);if(slotEnd>end)break;slots.push({clinicId,doctorId,startTime:slotStart,endTime:slotEnd});start.setMinutes(start.getMinutes()+duration);}return slots; }
  async createSlots(doctorUserId:number,date:string,startHour:number,endHour:number,duration=30,user:JwtUser){const clinicId=this.getClinicId(user);if(user.clinicRole!==ClinicRole.OWNER&&user.clinicRole!==ClinicRole.DOCTOR)throw new ForbiddenException('Doctor or owner access required');const doctor=await this.prisma.doctor.findFirst({where:{userId:doctorUserId,clinicId}});if(!doctor)throw new NotFoundException('Doctor not found');if(duration<=0||endHour<=startHour||endHour>24||startHour<0)throw new BadRequestException('Invalid schedule');const day=new Date(date);const start=new Date(day);start.setHours(startHour,0,0,0);if(start<=new Date())throw new BadRequestException('Cannot create slots in the past');const end=new Date(day);end.setHours(endHour,0,0,0);const existing=await this.prisma.appointmentSlot.count({where:{clinicId,doctorId:doctor.id,startTime:{gte:start,lt:end}}});if(existing)throw new BadRequestException('Slots already exist for this date');return this.prisma.appointmentSlot.createMany({data:this.buildSlotsForDay(clinicId,doctor.id,day,startHour,endHour,duration)});}
  async setWeeklyTemplate(doctorUserId:number,dayOfWeek:number,startHour:number,endHour:number,duration:number,note:string|undefined,user:JwtUser){const clinicId=this.getClinicId(user);const doctor=await this.prisma.doctor.findFirst({where:{userId:doctorUserId,clinicId}});if(!doctor)throw new NotFoundException('Doctor not found');if(dayOfWeek<0||dayOfWeek>6||startHour<0||endHour>24||endHour<=startHour||duration<=0||duration>(endHour-startHour)*60)throw new BadRequestException('Invalid schedule');return this.prisma.weeklyScheduleTemplate.upsert({where:{doctorId_dayOfWeek:{doctorId:doctor.id,dayOfWeek}},update:{startHour,endHour,duration,note},create:{clinicId,doctorId:doctor.id,dayOfWeek,startHour,endHour,duration,note}});}
  async setWeeklyRange(doctorUserId:number,fromDay:number,toDay:number,startHour:number,endHour:number,duration:number,note:string|undefined,user:JwtUser){if(fromDay>toDay)throw new BadRequestException('Invalid day range');const results=[];for(let day=fromDay;day<=toDay;day++)results.push(await this.setWeeklyTemplate(doctorUserId,day,startHour,endHour,duration,note,user));return results;}
  async deleteWeeklyTemplateDay(doctorUserId:number,dayOfWeek:number,user:JwtUser){const clinicId=this.getClinicId(user);const doctor=await this.prisma.doctor.findFirst({where:{userId:doctorUserId,clinicId}});if(!doctor)throw new NotFoundException('Doctor not found');const existing=await this.prisma.weeklyScheduleTemplate.findUnique({where:{doctorId_dayOfWeek:{doctorId:doctor.id,dayOfWeek}}});if(!existing||existing.clinicId!==clinicId)throw new NotFoundException('Schedule not found');await this.prisma.weeklyScheduleTemplate.delete({where:{id:existing.id}});return{message:'تم حذف اليوم من الجدول'};}
  async getWeeklyTemplate(doctorUserId:number,user:JwtUser){const clinicId=this.getClinicId(user);const doctor=await this.prisma.doctor.findFirst({where:{userId:doctorUserId,clinicId}});if(!doctor)throw new NotFoundException('Doctor not found');return this.prisma.weeklyScheduleTemplate.findMany({where:{clinicId,doctorId:doctor.id},orderBy:{dayOfWeek:'asc'}});}
  async getPublicWeeklyTemplate(doctorId:number,_user?:JwtUser){const doctor=await this.prisma.doctor.findFirst({where:{id:doctorId,clinic:{isActive:true}}});if(!doctor||!doctor.clinicId)throw new NotFoundException('Doctor not found');return this.prisma.weeklyScheduleTemplate.findMany({where:{clinicId:doctor.clinicId,doctorId},orderBy:{dayOfWeek:'asc'}});}
  async addLeave(doctorUserId:number,date:string,user:JwtUser){const clinicId=this.getClinicId(user);const doctor=await this.prisma.doctor.findFirst({where:{userId:doctorUserId,clinicId}});if(!doctor)throw new NotFoundException('Doctor not found');const leaveDate=new Date(date);if(await this.prisma.doctorLeave.findFirst({where:{clinicId,doctorId:doctor.id,date:leaveDate}}))throw new BadRequestException('Leave already exists');return this.prisma.doctorLeave.create({data:{clinicId,doctorId:doctor.id,date:leaveDate}});}
  async removeLeave(doctorUserId:number,date:string,user:JwtUser){const clinicId=this.getClinicId(user);const doctor=await this.prisma.doctor.findFirst({where:{userId:doctorUserId,clinicId}});if(!doctor)throw new NotFoundException('Doctor not found');const leave=await this.prisma.doctorLeave.findFirst({where:{clinicId,doctorId:doctor.id,date:new Date(date)}});if(!leave)throw new NotFoundException('Leave not found');await this.prisma.doctorLeave.delete({where:{id:leave.id}});return{message:'تم حذف الإجازة'};}
  async removeLeaveById(doctorUserId:number,leaveId:number,user:JwtUser){const clinicId=this.getClinicId(user);const doctor=await this.prisma.doctor.findFirst({where:{userId:doctorUserId,clinicId}});if(!doctor)throw new NotFoundException('Doctor not found');const leave=await this.prisma.doctorLeave.findFirst({where:{id:leaveId,doctorId:doctor.id,clinicId}});if(!leave)throw new NotFoundException('Leave not found');await this.prisma.doctorLeave.delete({where:{id:leave.id}});return{message:'تم حذف الإجازة'};}
  async getDoctorLeaves(doctorUserId:number,user:JwtUser){const clinicId=this.getClinicId(user);const doctor=await this.prisma.doctor.findFirst({where:{userId:doctorUserId,clinicId}});if(!doctor)throw new NotFoundException('Doctor not found');return this.prisma.doctorLeave.findMany({where:{clinicId,doctorId:doctor.id},orderBy:{date:'asc'}});}
}
