import { useState, useEffect } from "react";
import { useParams, Link } from "react-router-dom";
import api from "../api/axios";
import Avatar from "../components/Avatar";
import Stars from "../components/Stars";
import WeeklyScheduleTable from "../components/WeeklyScheduleTable";
import SocialLinks from "../components/SocialLinks";

function DoctorProfile() {
  const { id } = useParams(); const [doctor, setDoctor] = useState(null); const [reviewsData, setReviewsData] = useState(null); const [schedule, setSchedule] = useState([]); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  useEffect(() => { async function fetchData() { setLoading(true); setError(""); try { const [doctorRes, reviewsRes, scheduleRes] = await Promise.all([api.get(`/doctors/${id}`), api.get(`/reviews/doctor/${id}`), api.get(`/appointments/weekly-template/doctor/${id}`)]); setDoctor(doctorRes.data); setReviewsData(reviewsRes.data); setSchedule(scheduleRes.data); } catch (err) { setError(err.response?.data?.message || "تعذر تحميل بيانات الدكتور"); } finally { setLoading(false); } } fetchData(); }, [id]);
  if (loading) return <div className="page center"><p className="muted">جاري التحميل...</p></div>;
  if (error || !doctor) return <div className="page"><div className="alert alert-error">{error || "الدكتور غير موجود"}</div></div>;
  const stats = reviewsData?.statistics;
  return <div className="page"><div className="card" style={{ marginBottom: 24 }}><div className="row wrap" style={{ alignItems: "flex-start", gap: 18 }}><Avatar src={doctor.photoUrl} name={doctor.fullName} size={72} /><div style={{ flex: 1, minWidth: 220 }}><h1 style={{ marginBottom: 4 }}>د. {doctor.fullName}</h1><p className="muted" style={{ marginBottom: 4 }}>{doctor.specialty}</p>{doctor.clinic?.name && <div className="muted" style={{ fontSize: 14, marginBottom: 8 }}>📍 {doctor.clinic.name}{doctor.clinic.address ? ` — ${doctor.clinic.address}` : ""}</div>}{stats && stats.totalReviews > 0 && <div className="row" style={{ marginBottom: 8 }}><Stars value={stats.averageRating} /><span className="muted" style={{ fontSize: 14 }}>{stats.averageRating.toFixed(1)} ({stats.totalReviews} تقييم)</span></div>}{doctor.bio && <p style={{ marginBottom: 10 }}>{doctor.bio}</p>}<strong style={{ color: "var(--teal-800)", fontSize: 18 }}>{doctor.price} ج.م</strong><SocialLinks doctor={doctor} /></div><Link to={`/book?doctor=${doctor.id}`} className="btn btn-primary">احجز موعد</Link></div></div><div className="section"><h2>مواعيد العمل الأسبوعية</h2>{schedule.length === 0 ? <div className="empty-state">لسه الدكتور ما حددش جدول أسبوعي.</div> : <WeeklyScheduleTable template={schedule} />}</div><div className="section"><h2>تقييمات المرضى</h2>{!stats || stats.totalReviews === 0 ? <div className="empty-state">لسه مفيش تقييمات لهذا الدكتور.</div> : <div className="stack">{reviewsData.reviews.map(review => <div key={review.id} className="card"><div className="row between wrap" style={{ marginBottom: 6 }}><strong>{review.patient.fullName || review.patient.name}</strong><Stars value={review.rating} /></div><p style={{ marginBottom: review.doctorReply ? 10 : 0 }}>{review.comment}</p>{review.doctorReply && <div style={{ background: "var(--teal-50)", borderRadius: "var(--radius-sm)", padding: "10px 12px", marginTop: 8 }}><strong style={{ fontSize: 13.5, color: "var(--teal-800)" }}>رد الدكتور:</strong><p style={{ fontSize: 14, marginTop: 4 }}>{review.doctorReply}</p></div>}</div>)}</div>}</div></div>;
}
export default DoctorProfile;
