import { useState, useEffect } from "react";
import api from "../api/axios";

function MyMedicalRecords() {
  const [records, setRecords] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { async function fetchRecords() { try { const response = await api.get("/medical-records/my-records"); setRecords(response.data); } catch (err) { setError(err.response?.data?.message || "تعذر تحميل السجل الطبي"); } finally { setLoading(false); } } fetchRecords(); }, []);
  return <div className="page"><div className="page-head"><h1>سجلي الطبي</h1><p className="subtitle">كل التشخيصات والروشتات اللي كتبها لك الدكاترة من مختلف العيادات.</p></div>{error && <div className="alert alert-error">{error}</div>}{loading ? <p className="muted">جاري التحميل...</p> : records.length === 0 ? <div className="empty-state">مفيش سجلات طبية لسه.</div> : <div className="stack">{records.map(record => <div key={record.id} className="card"><div className="row between wrap" style={{ marginBottom: 10 }}><div><h3 style={{ marginBottom: 2 }}>{record.diagnosis}</h3><span className="muted" style={{ fontSize: 13.5 }}>د. {record.doctor?.fullName} — {record.clinic?.name || record.doctor?.clinic?.name || "العيادة"}</span><span className="muted" style={{ display: "block", fontSize: 12.5, marginTop: 3 }}>{new Date(record.createdAt).toLocaleDateString("ar-EG", { year: "numeric", month: "long", day: "numeric" })}</span></div></div>{record.notes && <p style={{ marginBottom: 8 }}><strong>ملاحظات: </strong>{record.notes}</p>}{record.additionalInstructions && <p style={{ marginBottom: 8 }}><strong>تعليمات إضافية: </strong>{record.additionalInstructions}</p>}{record.prescriptions?.length > 0 && <div style={{ marginTop: 12 }}><strong style={{ fontSize: 14, color: "var(--teal-900)" }}>الروشتة:</strong><div className="stack" style={{ marginTop: 8 }}>{record.prescriptions.map(rx => <div key={rx.id} className="rx-row" style={{ gridTemplateColumns: "1fr" }}><div className="row wrap between"><strong>{rx.medicineName}</strong><span className="muted" style={{ fontSize: 13.5 }}>{rx.dosage} — {rx.frequency} — لمدة {rx.duration}</span></div>{rx.instructions && <span className="muted" style={{ fontSize: 13 }}>{rx.instructions}</span>}</div>)}</div></div>}</div>)}</div>}</div>;
}
export default MyMedicalRecords;
